# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Ravshan S.K.
tagline:             'Economist, Blogger'
description:         'Thoughts, ideas, research, explanations around economics, philology, math, computers, literature.'
url:                 ''
baseurl:             ''
plugins: [jekyll-paginate]
paginate:            1
paginate_path: "page:num"

# About/contact
author:
  name:              Ravshan S.K.
  url:               
  email:             ravshansk@protonmail.com

# Custom vars
version:             1.0.0
