# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:			/:categories/:title:output_ext

# Setup
title:               R. Hojimatov
tagline:             'Economist'
description:         'Ravshanbek Khodzhimatov is an economist. His research interests are complexity economics, statistical learning, and numerical methods.' url:                 'http://hojimatov.com'
baseurl:             ''
plugins: [jekyll-seo-tag, jekyll-sitemap, jekyll-redirect-from]

# About/contact
author:
  name:              Ravshanbek Khodzhimatov
  url:               http://hojimatov.com
  email:             ravshan.personal@gmail.com

# Social media
twitter_username:	ravshansk

# Custom vars
version:             1.0.0
