# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Ravshan S.K. 
tagline:             'Statistical and Economic Consultancy'
description:         'economic analysis, statistical algorithms, economic consulting, statistical consulting, econometrics, statistics, economics'
url:                 ''
baseurl:             ''
plugins: [jekyll-seo-tag, jekyll-sitemap]

# About/contact
author:
  name:              Ravshanbek Khodzhimatov
  url:               http://ravshansk.com
  email:             rsk@ravshansk.com

# Custom vars
version:             1.0.0
