# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:			/:categories/:title:output_ext

# Setup
title:               Ravshan S.K. 
tagline:             'Economist'
description:         'Ravshanbek Khodzhimatov is an economist. His research interests are complexity economics, statistical learning, and numerical methods.'
url:                 'http://ravshansk.com'
baseurl:             ''
plugins: [jekyll-seo-tag, jekyll-sitemap, jekyll-redirect-from]

# About/contact
author:
  name:              Ravshanbek Khodzhimatov
  url:               http://ravshansk.com
  email:             rsk@ravshansk.com

# Social media
twitter_username:	ravshansk

# Custom vars
version:             1.0.0
